AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-contact-form-processor
  
  Sample SAM Template for lambda-contact-form-processor

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  WebsiteContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        FormProcessor:
          Type: Api
          Properties:
            Path: /contactProcessor
            Method: Post
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./handler
      Dockerfile: Dockerfile
Outputs:
  WebsiteContactFormAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/contactProcessor/"
  WebsiteContactFormFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt WebsiteContactFormFunction.Arn
  WebsiteContactFormFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt WebsiteContactFormFunctionRole.Arn