baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
class = 'text-white hover:text-gray-300'

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
class = 'text-white hover:text-gray-300'

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
class = 'text-white hover:text-gray-300'

[[menus.main]]
name = 'Media'
pageRef = '/media'
class = 'text-white hover:text-gray-300'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
