baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[[menus.main]]
name = 'HOME'
pageRef = '/'
class = 'text-white hover:text-gray-300 font-bold'

[[menus.main]]
name = 'ABOUT'
pageRef = '/about'
class = 'text-white hover:text-gray-300 font-bold'

[[menus.main]]
name = 'MIXES & EDITS'
pageRef = '/mixes'
class = 'text-white hover:text-gray-300 font-bold'

[[menus.main]]
name = 'PRESS KIT'
pageRef = '/presskit'
class = 'text-white hover:text-gray-300 font-bold'

[[menus.main]]
name = 'CONTACT'
pageRef = '/contact'
class = 'text-white hover:text-gray-300 font-bold'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
